replace python3 based urlencode & urldecode function with trurl
This should reduce external dependencies and make all of this slightly faster
and easier to maintain going forward.

diff --git a/stow/shell/dot-config/bash/functions b/stow/shell/dot-config/bash/functions
--- a/stow/shell/dot-config/bash/functions
+++ b/stow/shell/dot-config/bash/functions
@@ -189,6 +189,28 @@ function git-fetch {
 		xargs -P 8 -0 -I % bash -c 'git -C %/.. fetch --all --prune --prune-tags --quiet || echo "Failed updating: %"'
 }
 
+# URL-encode strings
+function urlencode {
+	local input=${1:-$(</dev/stdin)}
+	if ! command -v trurl >/dev/null; then
+		echo "trurl not installed, cannot URL-encode the data"
+		return 1
+	fi
+
+	trurl --url https://example.org --set fragment="${input}" --get '{fragment}' --urlencode
+}
+
+# URL-decode strings
+function urldecode {
+	local input=${1:-$(</dev/stdin)}
+	if ! command -v trurl >/dev/null; then
+		echo "trurl not installed, cannot URL-decode the data"
+		return 1
+	fi
+
+	trurl --url https://example.org --set fragment:="${input}" --get '{fragment}'
+}
+
 # `handle-secrets` is a wrapper function around `gitleaks` and allows you to
 # interactively go through any finding gitleaks detects in the supplied folder
 # and put them into a `.gitleaksignore` file with appropriate comments
